/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR_H_RPCGEN
#define _DIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef float Valor;

typedef char Operacion;

struct arg_simple {
	Valor val1;
	Valor val2;
	Operacion op;
};
typedef struct arg_simple arg_simple;

struct arg_vectorial {
	struct {
		u_int vec1_len;
		Valor *vec1_val;
	} vec1;
	struct {
		u_int vec2_len;
		Valor *vec2_val;
	} vec2;
	Operacion op;
};
typedef struct arg_vectorial arg_vectorial;

struct resp_vectorial {
	struct {
		u_int res_vec_len;
		Valor *res_vec_val;
	} res_vec;
};
typedef struct resp_vectorial resp_vectorial;

#define CALCULADORA_INTER 0x20000255
#define SIMPLE 1

#if defined(__STDC__) || defined(__cplusplus)
#define calculadora_simple 1
extern  float * calculadora_simple_1(arg_simple , CLIENT *);
extern  float * calculadora_simple_1_svc(arg_simple , struct svc_req *);
#define calculadora_vectorial 2
extern  resp_vectorial * calculadora_vectorial_1(arg_vectorial , CLIENT *);
extern  resp_vectorial * calculadora_vectorial_1_svc(arg_vectorial , struct svc_req *);
extern int calculadora_inter_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calculadora_simple 1
extern  float * calculadora_simple_1();
extern  float * calculadora_simple_1_svc();
#define calculadora_vectorial 2
extern  resp_vectorial * calculadora_vectorial_1();
extern  resp_vectorial * calculadora_vectorial_1_svc();
extern int calculadora_inter_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Valor (XDR *, Valor*);
extern  bool_t xdr_Operacion (XDR *, Operacion*);
extern  bool_t xdr_arg_simple (XDR *, arg_simple*);
extern  bool_t xdr_arg_vectorial (XDR *, arg_vectorial*);
extern  bool_t xdr_resp_vectorial (XDR *, resp_vectorial*);

#else /* K&R C */
extern bool_t xdr_Valor ();
extern bool_t xdr_Operacion ();
extern bool_t xdr_arg_simple ();
extern bool_t xdr_arg_vectorial ();
extern bool_t xdr_resp_vectorial ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIR_H_RPCGEN */
