/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "dir.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

float *
calculadora_simple_1(arg_simple arg1,  CLIENT *clnt)
{
	static float clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calculadora_simple,
		(xdrproc_t) xdr_arg_simple, (caddr_t) &arg1,
		(xdrproc_t) xdr_float, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resp_vectorial *
calculadora_vectorial_1(arg_vectorial arg1,  CLIENT *clnt)
{
	static resp_vectorial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calculadora_vectorial,
		(xdrproc_t) xdr_arg_vectorial, (caddr_t) &arg1,
		(xdrproc_t) xdr_resp_vectorial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
